<a href="https://colab.research.google.com/github/VarshiniAdurti28/Assignments_Varshini/blob/W1_Varshini/Assignment1_Varshini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **PyTorch Practice Assignment**
**Name**: Your Name Here

**Roll Number**: 231XX000

## **Instructions:**

- Copy this Notebook to your own Drive! You cannot directly modify it.
- Please show the output of the cells, in case of some operation. You can specify your own **non-trivial** test-case. Also, try and make your snippets into functions to organize your logic.
- You can use any number of cells for a question, you are not restricted to just 1 cell!
- **No using ChatGPT for this assignment**: we highly recommend using the [Pytorch Docs](https://pytorch.org/docs/stable/index.html) as your start reference, as well as the vast internet however. You can also contact any of your mentors for some hints/help!
- You can work on this assignment in Google Colab or on Your Local Machine!

### **Build Up Your Understanding**

In [2]:
import torch as tc
from torch import nn

import numpy as np

1. Write a PyTorch snippet to test whether none of the elements of a given tensor are zero.

In [3]:
#input
test=tc.randn(size=(3,4))
print(test)

# test[0][1]=0
result = tc.count_nonzero(test)

if(result==tc.numel(test)):
  print("no zeroes")
else:
  print("Some zeroes present")


# Alternate code:
# test=tc.randn(size=(3,4))

# train = tc.zeros_like(test)
# # test[0][1]=0
# result = tc.eq(test,train)

# if(True in result):
#   print("There are some zeroes")
# else:
#   print("no zeroes")


tensor([[ 0.0220,  0.7580, -1.1291, -1.3684],
        [-0.5436,  0.6477, -0.2597, -1.4197],
        [-0.6144,  0.7906,  0.2345,  0.3952]])
no zeroes


2. Write a PyTorch snippet to test element-wise for NaN of a given tensor.

In [4]:
test=tc.randn(size=(3,4))

result=tc.isnan(test)

print(test, result)


tensor([[-0.4230,  0.9936,  0.1127,  0.3816],
        [-1.3073,  0.5750, -0.6205,  0.2156],
        [ 0.2982, -0.9039, -0.5812, -2.0685]]) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


3. Write a PyTorch snippet to test whether two tensors are element-wise equal within a tolerance.

In [5]:
t1=tc.randn(size=(3,4))
t2=tc.randn(size=(3,4))
result=tc.eq(t1, t2)
if(False in result):
  print("They are not equal")
else:
  print("Equal")


They are not equal


4. Write a PyTorch snippet to create a tensor of 10 zeros, 10 ones, and 10 fives stacked on top of each other (try & accomplish everything using nested function calls).

In [6]:
def stacking(arr, axis, num:int):
  new=tc.full(size=(10,), fill_value=num, dtype=float)
  arr.append(new)
  ans=tc.stack((arr), axis)

  return ans


arr=[]
t1=stacking(arr, axis=0, num=0)

t1=stacking(arr, axis=0, num=1)
t1=stacking(arr, axis=0, num=5)


print(t1)



tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]], dtype=torch.float64)


5. Write a PyTorch snippet to generate a random number between 0 and 1.

In [7]:
num=tc.rand(size=(1,)).item()
print(num)


0.5498186945915222


6. Write a PyTorch snippet to generate a tensor of 15 random numbers from a standard normal distribution.

In [8]:
ans=tc.randn(size=(15,))
print(ans)

tensor([ 2.7229e-01,  5.6094e-01, -1.0192e+00, -3.9995e-01, -7.9636e-04,
        -7.8504e-01,  8.5387e-01, -1.1497e+00,  3.4527e-01, -5.4811e-01,
         1.4220e+00,  7.9760e-01,  9.8254e-02,  3.7483e-01,  7.6740e-01])


7. Write a Pytorch snippet to create a tensor of length 10 with values evenly distributed between 5 and 50.

In [9]:
from torch.distributions.uniform import Uniform

shape=(10,)
r1, r2= 5,51

ans=Uniform(r1, r2).sample(shape)
print(ans)


# r1=5
# r2=50

# t1=(r2-r1)*tc.rand(10,) + r1
# print(t1)


# https://stackoverflow.com/questions/44328530/how-to-get-a-uniform-distribution-in-a-range-r1-r2-in-pytorch

tensor([49.7710, 14.4707,  7.6884, 39.3230, 36.0904, 18.6832, 35.1529, 34.5167,
        37.3616, 19.0118])


*8*. Write a Pytorch program to create a tensor with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [10]:
num=tc.arange(0,21)
# print(num[9:16])

for i in range(9,16):
  num[i]=0-num[i]

print(num)


tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12, -13,
        -14, -15,  16,  17,  18,  19,  20])


9. Write a PyTorch snippet to create a 3x4 2-tensor filled with values from 10 to 21. Same but 12 to 24.

In [11]:
t1=tc.arange(10,22)
t1=t1.reshape([3,4])
print(t1)

t2=tc.arange(12,24)
t2=t2.reshape([3,4])
print(t2)

tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])
tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])


10. Write a PyTorch snippet to create a 10x10 2-tensor, in which the elements on the borders will be equal to 1, and inside 0.

In [12]:
t1=tc.zeros(size=(10,10))
t1[:, 0]=1
t1[:, 9]=1
t1[0,:]=1
t1[9,:]=1
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

11. Write a PyTorch snippet to create a 5x5 zero 2-tensor with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [13]:
t1=tc.zeros(size=(5,5))
for i in range(5):
  t1[i][i]=i+1

t1

tensor([[1., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0.],
        [0., 0., 3., 0., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 0., 5.]])

12. Write a PyTorch snippet to save a given tensor as a binary to a given path.

In [14]:
from pathlib import Path
save_path= "tensor_path"


t1=tc.tensor([1,2,3])

file_name = "tensors.pth"
save_path = file_name

tc.save(obj=t1, f=save_path)

13. Write a NumPy program to create a two-dimensional array of a specified format.

In [15]:
size= tuple(map(int, input().split()))
arr=np.empty(shape=size)
arr

 3 4


array([[5.04262191e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

##14. Write a PyTorch snippet to create a 2-tensor with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7) (mean, variance).

In [16]:
var=7 ** 0.5
print(var)
mn=200

y= var*tc.randn(8,5)+mn


y=y.reshape(shape=(8,5))

print(tc.mean(y), tc.var(y))

2.6457513110645907
tensor(200.1327) tensor(8.8028)


15. Write a PyTorch snippet to generate a uniform, non-uniform random sample from a given vector with and without replacement (do all 4 combinations possible).

16. Write a Pyorch snippet to create an nxn(input to function) tensor with random values. Create an array from the said array swapping first and last rows.

In [17]:
n=int(input())
arr=tc.randn(n,n)
result=arr.clone()
temp=result[0].clone()
result[0]=result[n-1]

result[n-1]=temp

print(arr, result)

3
tensor([[ 0.0089, -0.5818,  2.4819],
        [ 1.4197, -0.6601, -0.4689],
        [-0.0111, -0.7287, -1.5270]]) tensor([[-0.0111, -0.7287, -1.5270],
        [ 1.4197, -0.6601, -0.4689],
        [ 0.0089, -0.5818,  2.4819]])


17. Write a PyTorch snippet to sort a given tensor (1D or 2D) in ascending order.

In [18]:
t1=tc.randn(3,4)
format=t1.shape
print(t1)
t1=t1.reshape(t1.numel(),)
t1=(tc.sort(t1)).values
ans=t1.reshape(shape=(format))
print(ans)

tensor([[-1.3735, -0.5217,  0.3721,  0.2513],
        [ 1.0839,  0.7835,  0.3167, -2.2296],
        [ 0.5114, -0.7315, -0.1833, -0.5580]])
tensor([[-2.2296, -1.3735, -0.7315, -0.5580],
        [-0.5217, -0.1833,  0.2513,  0.3167],
        [ 0.3721,  0.5114,  0.7835,  1.0839]])


18. Write a PyTorch snippet to create a tensor of equal shape and data type for a given tensor (any dimensional)

In [19]:
t1=tc.randn(3,4, dtype=tc.float16)
t2=tc.randn(*(t1.shape), dtype=t1.dtype)
print(t2.shape, t2.dtype)

torch.Size([3, 4]) torch.float16


19. Write a PyTorch snippet to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
```py
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]
```

In [20]:
ans=tc.randn(8,8)

for i in range(8):
  if(i%2==0):
    ans[i]=tc.tensor([0,1,0,1,0,1,0,1])

  else:
    ans[i]=tc.tensor([1,0,1,0,1,0,1,0])

print(ans)


tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])


20. Write a Pytorch snippet to convert Centigrade to Fahrenheit and vice versa (controlled by a parameter). Ensure you operation is vectorized i.e **no explicit looping**

Sample Array: `[0, 12, 45.21, 34, 99.91]`

In [21]:
scale=input("Enter input scale (cel or far)\n")
sample=tc.tensor([0, 12, 45.21, 34, 99.91])


def convert(arr:tc.Tensor(), deg:str):
  if(deg=="cel"):
    new=(arr * 9)/5 + 32

  elif(deg=="far"):

    new=((arr-32)*5)/9


  return new


print(convert(sample, scale))


Enter input scale (cel or far)
far
tensor([-17.7778, -11.1111,   7.3389,   1.1111,  37.7278])


21. Write a PyTorch snippet to get the values of the elements that are bigger than a given *number* in a given tensor.

Original tensor:
```
[[ 0 10 20]
[20 30 40]]
```
Number: 10

Values bigger than 10 = `[20 20 30 40]`

In [22]:
t1=tc.tensor([[ 0,10,20],[20, 30, 40]])
num=int(input())

def check(tens, num):
  ans=t1[t1>10]

  return ans

print(check(t1, num))

10
tensor([20, 20, 30, 40])


22. Write a PyTorch snippet to create another shape from an array without changing its data. After carrying out the operation, change the data in one place and see if the other tensor changes

Reshape 3x2:
```
[[1 2]
[3 4]
[5 6]]
```
Reshape 2x3:
```
[[1 2 3]
[4 5 6]]
```

In [23]:
t1=tc.tensor([[1,2],[3,4],[5,6]])
t2=t1.reshape(shape=(2,3))
t2[1][0]=54
print(t2, t1)


#Value changes when you use reshape

tensor([[ 1,  2,  3],
        [54,  5,  6]]) tensor([[ 1,  2],
        [ 3, 54],
        [ 5,  6]])


23. Write a PyTorch snipppet to change an tensor's data type.
```
[[ 2 4 6]
[ 6 8 10]]
```
Data type of the array x is: `int32`

New Type: `float64`
```
[[ 2. 4. 6.]
[ 6. 8. 10.]]
```

In [24]:
t1=tc.tensor([[2, 4, 6],[ 6,8,10]], dtype=tc.float64)

print(t1)

#or

t1=tc.tensor([[2, 4, 6],[ 6,8,10]])
t1=t1.type(tc.float64)
print(t1)



tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]], dtype=torch.float64)


24. Write a PyTorch snippet to insert a new axis within a 2-tensor, based on a **parameter**.

Ex: If 2-tensor has shape (3, 4).

Then, new shape can be (1, 3, 4), (3, 1, 4), or (3, 4, 1) depending on....

In [25]:
t1=tc.randn(3,4)
param=int(input("Enter values between 1 to 3\n"))

def newdim(tens, para):
  if(para==1):
    ans=t1[None, ]
  elif(para==2):
    ans=t1[:, None, ]
  else:
    ans=t1[:, :, None]

  return ans

print(newdim(t1, param).shape)

Enter values between 1 to 3
1
torch.Size([1, 3, 4])


25. Write a PyTorch snippet to stack tensors based on a parameter, **axis**.
First discover what this means with 2-tensors, then extend it to 3-tensors. Print your findings.

Sample Output:

Original tensors:

Tensor-1
```
[[0 1 2]
[3 4 5]
[6 7 8]]
```
Tensor-2
```
[[ 0 3 6]
[ 9 12 15]
[18 21 24]]
```
Stack tensors such that axis=1:
```
[[ 0 1 2 0 3 6]
[ 3 4 5 9 12 15]
[ 6 7 8 18 21 24]]
```

In [26]:
#In 2D
t1=tc.tensor([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
t2=tc.tensor([[ 0, 3, 6],[ 9, 12, 15],[18, 21, 24]])
print(t1,t2)
ax=int(input("Enter 0 or 1 \n"))

def stacking(tens:tuple, axis:int):
  new=tc.cat(tens, axis=axis) #Use tc.stack(same syntax) for stacking, however this adds another dimension while cat()stacks the tensors along an existing dimension

  return new


print(stacking((t1,t2), ax))
print("\n")
#In 3D
t1=tc.tensor([[[0, 1, 2],[3, 4, 5],[6, 7, 8]], [[45,54,71],[48,65,91],[75,235,64]]])
t2=tc.tensor([[[ 0, 3, 6],[ 9, 12, 15],[18, 21, 24]], [[7,1,3],[11,55,81],[9,23,14]]])
print(t1,t2)
ax=int(input("Enter 0 or 1 or 2\n"))

print(stacking((t1,t2), ax))


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) tensor([[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])
Enter 0 or 1 
0
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24]])


tensor([[[  0,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8]],

        [[ 45,  54,  71],
         [ 48,  65,  91],
         [ 75, 235,  64]]]) tensor([[[ 0,  3,  6],
         [ 9, 12, 15],
         [18, 21, 24]],

        [[ 7,  1,  3],
         [11, 55, 81],
         [ 9, 23, 14]]])
Enter 0 or 1 or 2
1
tensor([[[  0,   1,   2],
         [  3,   4,   5],
         [  6,   7,   8],
         [  0,   3,   6],
         [  9,  12,  15],
         [ 18,  21,  24]],

        [[ 45,  54,  71],
         [ 48,  65,  91],
         [ 75, 235,  64],
         [  7,   1,   3],
         [ 11,  55,  81],
         [  9,  23,  14]]])


26. Write a PyTorch snippet to extract the **m**th to **n**th elements of the **m**th to **n**th rows from the **m**th to nth elemnts of given 3-tensor, of shape `(p, q, r)` where m, n < p, q, r.

Take a 3-tensor of (say) size `(5,6,7)` and `(m, n)` = `(4, 5)` as a test case!

In [27]:
sample=tc.randn(size=(5,6,7))
(m,n)=(2,4)
m-=1
n-=1

arr=sample[m:n, m:n, m:n]


print(sample)

print("\n\n")

print(arr)



tensor([[[ 2.2881,  0.9049,  0.1925,  1.7315, -0.1165,  0.3394, -0.3963],
         [ 0.4520, -2.3000, -1.1805,  1.1503,  0.3258,  1.2452, -0.7329],
         [ 0.6899,  1.1459, -0.4978,  0.2343,  1.0937,  1.5564, -0.0677],
         [ 0.7744,  0.3710,  0.8320, -0.7594, -2.0406,  0.2863,  0.8900],
         [ 0.1792, -1.0750, -2.2565, -1.4910,  0.0581, -0.1127, -2.7266],
         [ 0.6580, -0.7687,  0.1454,  1.4755,  0.0122,  2.2230,  0.0255]],

        [[ 0.7659,  1.2169,  0.8250, -0.3172, -0.8260,  0.4305,  0.5375],
         [ 0.0919, -0.3304,  0.1987, -1.1169, -2.1782,  2.5617,  0.6428],
         [-0.3021, -0.2692, -0.2003, -1.5948, -3.1239,  0.4626,  0.1085],
         [-1.8789,  0.1045,  0.3505,  0.8006, -0.2943,  0.0604, -0.7830],
         [ 0.4381, -0.4382, -1.0593,  1.1172, -1.0579,  1.0872, -0.3478],
         [ 0.4097,  0.9601,  0.6443,  0.2239,  1.1291, -0.5381, -0.7002]],

        [[-1.1243,  0.4248, -1.2714, -0.2450,  1.4358, -1.8282, -1.0586],
         [-0.3022,  1.5405, -0.250

### **Test your Understanding**

1. Given a 3D tensor of shape `(a, b, c)`*italicised text*, permute its axes to obtain tensors of all other shape combinations (i.e 5).

In [28]:
from itertools import permutations
a,b,c = map(int,input().split())

t=tc.randn(size=(a,b,c))
print(t)
order=permutations([0,1,2])

final=[]

for i in order:
  t1=tc.permute(t, tuple(i))
  final.append(t1)


print("\n")

for i in final:
  print(i, i.shape)


1 2 3
tensor([[[ 0.8100, -1.2480,  0.2738],
         [ 0.0237,  0.3249,  0.1941]]])


tensor([[[ 0.8100, -1.2480,  0.2738],
         [ 0.0237,  0.3249,  0.1941]]]) torch.Size([1, 2, 3])
tensor([[[ 0.8100,  0.0237],
         [-1.2480,  0.3249],
         [ 0.2738,  0.1941]]]) torch.Size([1, 3, 2])
tensor([[[ 0.8100, -1.2480,  0.2738]],

        [[ 0.0237,  0.3249,  0.1941]]]) torch.Size([2, 1, 3])
tensor([[[ 0.8100],
         [-1.2480],
         [ 0.2738]],

        [[ 0.0237],
         [ 0.3249],
         [ 0.1941]]]) torch.Size([2, 3, 1])
tensor([[[ 0.8100,  0.0237]],

        [[-1.2480,  0.3249]],

        [[ 0.2738,  0.1941]]]) torch.Size([3, 1, 2])
tensor([[[ 0.8100],
         [ 0.0237]],

        [[-1.2480],
         [ 0.3249]],

        [[ 0.2738],
         [ 0.1941]]]) torch.Size([3, 2, 1])


2. Given a 4D tensor of shape `(2, 3, 4, 5)`, transpose it to obtain a tensor of shape `(2, 4, 5, 3)`. Also explore what is_contiguous() means...

In [29]:
t=tc.randn(size=(2,3,4,5))

ans=tc.permute(t, (0,2,3,1))

print(ans.shape)


#or

new= tc.transpose(t,1,2)
new=tc.transpose(new, 2,3)

print(new.shape)


torch.Size([2, 4, 5, 3])
torch.Size([2, 4, 5, 3])


3. Given two tensors, one of shape (n, 1) and another of shape (m, ), perform an element-wise addition.

In [30]:
m,n = map(int, input().split())

t1=tc.randn(size=(m,))
t2=tc.randn(size=(n,1))
print(t1, t2)


def add(t1, t2, n, m):
  new1=t1.repeat(n, 1)
  new2=t2.repeat(1, m)

  ans=new1+new2

  return ans



manual_add=add(t1, t2, n, m)  #BY MANUAL BROADCASTING
print(manual_add)

print("\n")
simple_add=t1+t2
print(simple_add)


3 4
tensor([ 0.2036,  0.9888, -1.1898]) tensor([[ 0.1804],
        [ 0.1813],
        [-1.8153],
        [ 0.2515]])
tensor([[ 0.3840,  1.1693, -1.0093],
        [ 0.3849,  1.1701, -1.0084],
        [-1.6117, -0.8265, -3.0051],
        [ 0.4551,  1.2403, -0.9383]])


tensor([[ 0.3840,  1.1693, -1.0093],
        [ 0.3849,  1.1701, -1.0084],
        [-1.6117, -0.8265, -3.0051],
        [ 0.4551,  1.2403, -0.9383]])


4. Given a 3D tensor of shape `(4, 4, 4)`, extract a sub-tensor of shape `(2, 2, 2)` starting from the element at index `(1, 1, 1)`**bold text**.

In [37]:
arr=tc.randn(size=(4,4,4))

arr2= arr[1:, 1:, 1:]

final=arr2[0:2, 0:2, :]

print(f"{arr}\n{arr2}\n\n\n{final}")



tensor([[[-0.0271, -0.3532,  1.4639,  0.1729],
         [ 1.0514,  0.0075, -0.0774,  0.6427],
         [ 0.5655,  0.5058,  0.2225, -0.9143],
         [ 1.4840, -0.9109, -0.5291, -0.8051]],

        [[ 0.4323, -0.1250,  0.7821,  0.5635],
         [ 1.8582,  1.0441, -0.8638,  0.8351],
         [ 0.2466, -1.9776,  0.0179, -1.4129],
         [-1.8791, -0.1798,  0.7904,  0.5239]],

        [[-0.7470,  1.7093,  0.0579,  0.8637],
         [-0.5890, -1.0340, -0.2179,  0.7987],
         [ 1.1566,  0.2691, -0.0366, -0.4808],
         [ 0.3163,  0.3866,  0.7337,  0.2510]],

        [[-0.1293, -0.7150, -0.0476,  0.5230],
         [ 0.9717, -0.2779, -0.6116, -0.5572],
         [ 0.1016,  1.3433,  0.7133,  0.3463],
         [-0.5402,  0.8569, -0.6721,  1.0682]]])
tensor([[[ 1.0441, -0.8638,  0.8351],
         [-1.9776,  0.0179, -1.4129],
         [-0.1798,  0.7904,  0.5239]],

        [[-1.0340, -0.2179,  0.7987],
         [ 0.2691, -0.0366, -0.4808],
         [ 0.3866,  0.7337,  0.2510]],

        

5. Given a 2-tensor of arbitrary shape, rotate it 90 degrees anticlockwise.



In [32]:
t1=tc.randn(size=(3,4))

ans=tc.rot90(t1)
print(t1,ans)

tensor([[-0.9804,  1.2485, -1.6569, -1.0198],
        [-0.2970, -1.0201,  0.5458,  2.0601],
        [ 1.7141,  0.3903,  0.0313,  1.6964]]) tensor([[-1.0198,  2.0601,  1.6964],
        [-1.6569,  0.5458,  0.0313],
        [ 1.2485, -1.0201,  0.3903],
        [-0.9804, -0.2970,  1.7141]])


### **EVEN I HAD TO THINK...**

1. Implement a custom operation that computes the **element-wise** **sine** of a tensor *and* its **gradient** using torch.autograd.Function.
- You need to implement both the forward() and backward() methods.
- For an example, look no further than the [PyTorch docs](https://pytorch.org/docs/stable/autograd.html#function)!
- Test it out on a matrix of arbitrary size!

In [33]:
tc.manual_seed(42)
test= tc.randn(size=(3,4), requires_grad=True)

sine= tc.sin(test)
print(sine)

out= tc.sum(sine)

# final=tc.autograd.grad(out, test)

# print(final)


final=tc.autograd.backward(out, inputs=test)
print(final)



tensor([[ 0.3304,  0.1285,  0.2323,  0.2283],
        [-0.9013, -0.1853,  0.8036, -0.5956],
        [ 0.4454,  0.2642,  0.5098,  0.7238]], grad_fn=<SinBackward0>)
None


2. One of the most important aspects of improving model performance ins normalization. Implement a custom NN normalization layer that performs either a **batch** or **layer** normalization (based on a **dim** parameter)and integrate it into a simple feedforward neural network.
- Note that you dont need to implement any backward() here, for simplicity.
- Consider your input tensor to the neural network as of shape (m, n) where m is num of examples, n is num of features.
- Which value of **dim** leads to batch and layer normalization?

In [34]:
sample=tc.rand(size=(3,4))

#Batch Normalisation, dim=1

batch=tc.nn.functional.normalize(sample, dim=1)

#Layer Normalisation

layer=tc.nn.functional.normalize(sample, dim=0)

# print(f"sample: \n{sample}\nBatch Normalised:\n{batch}\nLayer Normalised:\n{layer}")


class model(nn.Module):
  def __init__(self, inp):
    super().__init__()
    self.input=(inp.shape)[1]


    self.linear=nn.Sequential(
        nn.Linear(
          in_features=self.input,
          out_features=6
     ),
        nn.Linear(
          in_features=6,
          out_features=1
      )
    )

  def forward(self, inp):
    return self.linear(inp)


ans=model(batch)

ans.state_dict()


OrderedDict([('linear.0.weight',
              tensor([[ 0.0779,  0.4040,  0.0547, -0.1577],
                      [ 0.1343, -0.1356,  0.2104,  0.4464],
                      [ 0.2890, -0.2186,  0.2886,  0.0895],
                      [ 0.2539, -0.3048, -0.4950, -0.1932],
                      [-0.3835,  0.4103,  0.1440,  0.2071],
                      [ 0.1581, -0.0087,  0.3913, -0.3553]])),
             ('linear.0.bias',
              tensor([ 0.0315, -0.3413,  0.1542, -0.1722,  0.1532, -0.1042])),
             ('linear.1.weight',
              tensor([[ 0.3386, -0.2420, -0.2435, -0.2435,  0.3672,  0.1360]])),
             ('linear.1.bias', tensor([0.3928]))])

3. Given a 4D tensor of shape (2, 3, 4, 5), create a mask that sets all elements in positions where the sum of indices is even to zero.

In [35]:
sample=tc.randn(size=(2,3,4,5))

indices=tc.nonzero(sample)
indices


for index in indices:
  if(index.sum()%2==0):
    sample[list(index)]=0


sample


tensor([[[[ 0.0000,  0.0087,  0.0000,  0.1971,  0.0000],
          [ 0.3383,  0.0000,  0.0109,  0.0000, -0.0898],
          [ 0.0000, -0.5644,  0.0000, -1.4692,  0.0000],
          [ 0.7440,  0.0000, -0.6021,  0.0000,  0.4048]],

         [[-1.3543,  0.0000,  0.4747,  0.0000,  1.2683],
          [ 0.0000,  0.0981,  0.0000, -1.3527,  0.0000],
          [ 0.5526,  0.0000,  0.5743,  0.0000, -0.3576],
          [ 0.0000,  0.5886,  0.0000,  0.4098,  0.0000]],

         [[ 0.0000,  0.3499,  0.0000, -0.1693,  0.0000],
          [ 4.0356,  0.0000, -0.0127,  0.0000,  1.0131],
          [ 0.0000,  0.5177,  0.0000, -0.5797,  0.0000],
          [ 1.9312,  0.0000, -0.4752,  0.0000,  0.2704]]],


        [[[-0.5628,  0.0000,  0.4405,  0.0000, -0.0606],
          [ 0.0000,  0.8187,  0.0000,  0.3449,  0.0000],
          [-0.1163,  0.0000, -0.0467,  0.0000, -0.5665],
          [ 0.0000,  0.2625,  0.0000,  0.5214,  0.0000]],

         [[ 0.0000, -2.2933,  0.0000, -0.4257,  0.0000],
          [-0.1933,  

4. Given two tensors, one of shape `(3, 1, 4)` and another of shape `(1, 5, 1)`, compute their element-wise multiplication using broadcasting and then sum over specific axes to obtain a tensor of shape `(3, 5)`.

In [38]:
#Element wise multiplication

t1=tc.randn(size=(3,1,4))
t2=tc.randn(size=(1,5,1))

simple_mult=t1*t2

new1=t1.repeat(1,5,1)
new2=t2.repeat(3,1,4)

manual_mult= new1*new2


print(f"{simple_mult}\n{manual_mult}")


#Sum to get the shape (3,5)
ans=tc.sum(simple_mult, dim=2)
final=ans.squeeze()

print("\n")

print(final)



tensor([[[ 0.0352, -0.0883,  0.1731, -0.0282],
         [ 0.0199, -0.0499,  0.0978, -0.0159],
         [-0.0752,  0.1887, -0.3701,  0.0603],
         [ 0.3915, -0.9825,  1.9270, -0.3142],
         [-0.2190,  0.5496, -1.0780,  0.1757]],

        [[-0.0173,  0.1784, -0.0661,  0.0146],
         [-0.0098,  0.1007, -0.0373,  0.0083],
         [ 0.0370, -0.3814,  0.1412, -0.0313],
         [-0.1928,  1.9854, -0.7353,  0.1630],
         [ 0.1079, -1.1107,  0.4113, -0.0912]],

        [[ 0.0291,  0.0087, -0.0320,  0.1500],
         [ 0.0164,  0.0049, -0.0181,  0.0847],
         [-0.0621, -0.0187,  0.0684, -0.3206],
         [ 0.3235,  0.0973, -0.3561,  1.6692],
         [-0.1810, -0.0544,  0.1992, -0.9337]]])
tensor([[[ 0.0352, -0.0883,  0.1731, -0.0282],
         [ 0.0199, -0.0499,  0.0978, -0.0159],
         [-0.0752,  0.1887, -0.3701,  0.0603],
         [ 0.3915, -0.9825,  1.9270, -0.3142],
         [-0.2190,  0.5496, -1.0780,  0.1757]],

        [[-0.0173,  0.1784, -0.0661,  0.0146],
     